package model;
// Generated Sep 28, 2018 11:41:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer loginId;
     private String username;
     private String password;
     private String type;
     private Set banks = new HashSet(0);
     private Set users = new HashSet(0);

    public Login() {
    }

    public Login(String username, String password, String type, Set banks, Set users) {
       this.username = username;
       this.password = password;
       this.type = type;
       this.banks = banks;
       this.users = users;
    }
   
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getBanks() {
        return this.banks;
    }
    
    public void setBanks(Set banks) {
        this.banks = banks;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}
